"use client";

import { useState } from "react";
import { getNearbySafePlaces, getPrivacySettings, updatePrivacySettings, type PrivacySettings, type SafePlace } from "@/lib/safe-places";
import type { Coordinate } from "@/lib/navigation";

export function SafetyControls({ currentLocation, onNavigate }: { currentLocation: Coordinate | null; onNavigate: (coordinate: Coordinate, label: string) => void }) {
  const [resources, setResources] = useState<SafePlace[] | null>(null);
  const [privacy, setPrivacy] = useState<PrivacySettings | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [privacyError, setPrivacyError] = useState<string | null>(null);
  async function loadResources() { if (!currentLocation) { setError("Use current location before searching nearby resources."); return; } setLoading(true); setError(null); try { setResources((await getNearbySafePlaces(currentLocation)).resources); } catch (e) { setError(e instanceof Error ? e.message : "Resources are unavailable."); } finally { setLoading(false); } }
  async function loadPrivacy() { try { setPrivacy(await getPrivacySettings()); } catch (e) { setPrivacyError(e instanceof Error ? e.message : "Privacy settings are unavailable."); } }
  async function toggle(field: keyof Pick<PrivacySettings, "location_sharing_enabled" | "trusted_contact_sharing_enabled" | "emergency_sharing_enabled">) { if (!privacy) return; try { setPrivacy(await updatePrivacySettings({ [field]: !privacy[field] })); } catch (e) { setPrivacyError(e instanceof Error ? e.message : "Privacy settings could not be updated."); } }
  return <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Nearby assistance resources</h2><p className="mt-1 text-xs text-slate-500">Synthetic demo resources ranked by distance; not a safety guarantee.</p></div><button type="button" onClick={() => void loadResources()} disabled={loading} className="rounded-lg border border-indigo-200 px-3 py-2 text-xs font-semibold text-indigo-700 disabled:opacity-50">{loading ? "Loading…" : "Find nearby"}</button></div>{error && <p role="alert" className="mt-3 text-xs text-rose-700">{error}</p>}{resources && resources.length === 0 && <p className="mt-3 text-sm text-slate-500">No demo resources matched this radius.</p>}{resources && <div className="mt-3 space-y-2">{resources.map((resource) => <div key={resource.id} className="flex items-center justify-between gap-3 rounded-lg border border-slate-100 p-3"><div><p className="text-sm font-medium">{resource.name}</p><p className="text-xs text-slate-500">{resource.category.replaceAll("_", " ")} · {Math.round(resource.distance_meters)} m</p></div><button type="button" onClick={() => onNavigate({ latitude: resource.latitude, longitude: resource.longitude }, resource.name)} className="text-xs font-semibold text-indigo-700 underline">Navigate</button></div>)}</div>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Privacy controls</h2><p className="mt-1 text-xs text-slate-500">Sharing is disabled by default. Prototype-global settings.</p></div><button type="button" onClick={() => void loadPrivacy()} className="text-xs font-semibold text-indigo-700 underline">Load settings</button></div>{privacy && <div className="mt-3 space-y-2">{([["location_sharing_enabled", "Live location sharing"], ["trusted_contact_sharing_enabled", "Trusted-contact sharing"], ["emergency_sharing_enabled", "Emergency sharing"]] as const).map(([field, label]) => <label key={field} className="flex items-center justify-between rounded-lg border border-slate-100 p-3 text-sm"><span>{label}</span><input type="checkbox" checked={privacy[field]} onChange={() => void toggle(field)} /></label>)}</div>}{privacyError && <p role="alert" className="mt-3 text-xs text-rose-700">{privacyError}</p>}</section></div>;
}
